---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traggo-data-claim
  annotations:
    nfs.io/storage-path: "traggo"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
