---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: firefly-iii-values
    namespace: default
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
