---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.sops.yml
configMapGenerator:
  - name: firefly-iii-values
    namespace: default
    files:
      - values.yml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: PersistentVolumeClaim
      name: firefly-iii
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          nfs.io/storage-path: "firefly_iii_uploads"
