apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii-secret
  namespace: default
stringData:
  APP_KEY: ENC[AES256_GCM,data:E4jGhB8zJidEIbvU0BICshV5lzT3owK+RTPeoqKWyjo=,iv:TLxqmcXexnXsCdGsJqb0RNnfZ+B1gvzxURA6uIhA2iQ=,tag:Kt572QE9ue13WZgMRjRfLQ==,type:str]
  STATIC_CRON_TOKEN: ENC[AES256_GCM,data:iAXqDn0jYZWeNhfRSs6RqnOA5f8WIskAcIFbOf5BeTU=,iv:lByP34xjEh+yspiVwfcvCBwaBi2PBZnl/JCngaRMruA=,tag:K+bYt6zsqJppUZ7KyVnBvg==,type:str]
  DB_CONNECTION: ENC[AES256_GCM,data:QBWa5qQ=,iv:9De15eLhKzaEzhn7NFvbC9/Rv6cR3i3Uo++LOmWn1AI=,tag:ih1V4KjBC5MzgQLFyfm9Og==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:8K4Lm793+N1dMQ==,iv:XdjTC5sUm5sQJMDjquAuz0+/jJ52+HJrDPbxKwPU8Fc=,tag:borvNLnnZPp9aVQqf06Ddw==,type:str]
  DB_HOST: ENC[AES256_GCM,data:vSA0wnxxVjiYiWUG,iv:dimqBzV0mFBMFAYv/fL8tNU5xHIUWZLh5w6ISnfa8s0=,tag:IDCrkvEGkI/2ReTzBc271w==,type:str]
  DB_PORT: ENC[AES256_GCM,data:EghivA==,iv:rOVOfQM9RA/nf8zT+5hzNuTy0I/MF1h8ZLwaawWS+zA=,tag:OvhkUX8DxgOrl5vc2xnvcg==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:evNBGY6HDw==,iv:tYBxPKqKm2olU7eBmkdGi77p4V//pJuEcLsMFUzr+J8=,tag:YLZRjG/K9gWVwump2Imv+A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:b8hT8rMIk0c=,iv:9Y8/oRCfRtNva2myHuN5CaFDsXIX4egIBv64xKM2mf8=,tag:XFz0GgFRrz1Ah7aKm+DSkw==,type:str]
  MAIL_MAILER: ENC[AES256_GCM,data:Xp4Q0g==,iv:EAJ2vic+Gz2XqRYA4pu3/e/AvL1kWH5U9kTqo5aUXpQ=,tag:kancZgz+/ro9x1jCNJxstA==,type:str]
  MAIL_HOST: ENC[AES256_GCM,data:wh3o4OPv4cT4WmeXadQ=,iv:UvojcmlOsxGitDXkCRTQTZ84dyfJR/JwNPQijgWYp6k=,tag:kK0zEkNxNsT3CPlzKjPnOQ==,type:str]
  MAIL_PORT: ENC[AES256_GCM,data:AOBi,iv:jGaQTAyLJ6MJ33ZzF2HKaHpEL0iw783cTxG0Kf5nXPQ=,tag:gqiRE6HTFZd5tR2Kz1Q+2g==,type:str]
  MAIL_ENCRYPTION: ENC[AES256_GCM,data:UOp+,iv:aT+FeHD+kX4pN4LOa/wJEfc8cEQgJXkmuQ2ioVgIfMg=,tag:7njzQxW99qOeWOJM9MD3lw==,type:str]
  MAIL_FROM: ENC[AES256_GCM,data:bsIycGzYYzUi88MGU1ZX8PCeYdg0vbE1+PpS20oQ75VUBizykQ==,iv:e4C6UbRNKeFa4lgKPMCwz45guQB5mKekG+37JFYoatI=,tag:dM6VjQqzXcEcRKWEPAH57g==,type:str]
  MAIL_USERNAME: ENC[AES256_GCM,data:p9mxKeGggX/8c3899SeDjDXJImnfGIzyyfGW+KU=,iv:EM6bp6ldKfdS/tXRysca+7Xq0ciEi28ECwy/FqsC3q4=,tag:ymfBZ7Gwsxz5d6/WfLibIQ==,type:str]
  MAIL_PASSWORD: ENC[AES256_GCM,data:FlUFC6vcavHkr5ziLsx7jA==,iv:uD1a/A9SNREWuhLbeWp2Njz4NOnjXLf4gpIUGUGaUHQ=,tag:HChDPvTr+do/UUwkct4+7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN2RacXVCRHhTQ1lIR29Z
        dDJWcDk4QUNZK1RTT0thYlpmcmREcndRNTBNCnNCVzVQTmY1d1R2V09VREJESHdy
        bEp6UVVWcHl4SzU2c3ZxMDZiYnh1OVEKLS0tIHpoRkt0bGVPRm9JNlhIVWlxSkdk
        QVdrbFh4cll0WGVIbTNCQlJYN00rZWsK36aQ3AVw6hmQx0tauh5dQ1IBMmc0ESPq
        efTzLb6WwRlTdQ5PziMTU19wDHmTzC/RscaZOMHB2+1zFy8e2vq0+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T05:24:54Z"
  mac: ENC[AES256_GCM,data:G/wnJMHcRrTOVze7hKT8jsXeNLQ/Ta0K2pELwJ59j1uYSd+NV3ApbYiJcfpTzpEFjL+SzykbBELuKiNc2mpLMTL6FHrTy9JmLUPZsb7OJ+o9ojBE4rd4/7/Wh+xBiG6pVrB16ZzeVaqYO+X0rlmoyCfTRYM26jUlrMVu2nANhfU=,iv:fymAoLSEXR6iBfd+fWUlg8FbA4rjFtZOsxiJz3P8TL4=,tag:8hf1XS4zCA3haHrHbIuLDQ==,type:str]
  version: 3.13.3
