apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secret
  namespace: default
stringData:
  APP_URL: ENC[AES256_GCM,data:MdTbypWTMW4sqiJKPF2gUvOS6uc=,iv:1S6xBrraoSNw6+6ouCqw/xMhyppZi4JzIfSCU3g+Oj4=,tag:euUSaN3zB2xbFCe3fTLUlA==,type:str]
  DB_HOST: ENC[AES256_GCM,data:5AQUgxXfX9FZLLzO,iv:NzdLDCsrXbnxnRBPSOt/LgE9V8BMD+gPPFUVJgQbFi4=,tag:EhUihyU09bVkBMNCxWtZNw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:n1AMNQ==,iv:3lEriu5WJd3QO80Khvgyu7PihyI+fQHE6KAIJ6VDXQU=,tag:qW3qcWYT/gfrGrVtLL7nxg==,type:str]
  DB_USER: ENC[AES256_GCM,data:FFa3VQ8uL+m/,iv:tPPMCMnOHhEj13+tmryLQ9zAwd5C8n7NhhedAOWJWSo=,tag:VDL9UAzFkW9qj+7pFfgUvQ==,type:str]
  DB_PASS: ENC[AES256_GCM,data:3arJGj6pHBOkmK7HyA==,iv:f+yTbAslqe4AlXq/odH8nyhJRzbySyfGesWi2yy/6sE=,tag:33bfJeRDEY91+A6bu1V66Q==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:lfPWolTgr0Ur,iv:w+2xbbzcDY66Dpm8PcAJLyNDoulkbtSExBuaUf7S7o0=,tag:uKIGTzvKFnCIhAto5U3vdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1azAwUkkxTG5MWVVvT3J4
        cUE5QktFNk5JUVlkZTQrWXJ1b3hPR3V0b1ZjCldIYXI1cHZ0QWd5VzNSZld4UG12
        YlJ2N2hmNnNUOUNRaHdZSjhQbWpkR28KLS0tIHhoWTUxYXhLZE9QU2I2MDhSL0Ja
        V25DUlpQb0pKNFlDd0ZSWGpuOS9lTjAKPgM+tsqEsC5Ev1jKrSM/mrXuThwQ7LzS
        t3pt9nPQu16F7S8+UzFVMmKyaSUBgB8QBPBA6ksKweI9PGx0Bn1wag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T06:01:07Z"
  mac: ENC[AES256_GCM,data:7HsGP2bJ173auptJivGXSKefQGtij45rnSbAbmyjLfXUL4QvsV1iBRIQaM03/OOirvs7a/pz6qBIzxb2Ton8PC//uMqdAqP8YwjE9BvlAo3wFHpCshbCwEP7fX0Oi2Im290/xBUa8DuihV+94nUJe/JyZ8AcjgrCV41z6l+A598=,iv:OOPW/cRiDkM69ucPuMVwhHyOO3vWpz5Wv3d3V/PXGUg=,tag:X4MYAW6UojiHuyafXsQynA==,type:str]
  version: 3.13.3
