---
- name: Check if entware is already installed
  ansible.builtin.stat:
    path: "{{ entware_root }}/opt/etc/entware_release"
  register: entware_release

- name: Create root folder
  ansible.builtin.file:
    path: "{{ entware_root }}/opt"
    state: directory
    mode: u=rwx,g=r-x,o=r-x

- name: Mount to /opt
  ansible.posix.mount:
    src: "{{ entware_root }}/opt"
    path: /opt
    opts: bind
    state: mounted
    fstype: none

- name: Download entware installer
  when: not entware_release.stat.exists
  ansible.builtin.get_url:
    url: "http://bin.entware.net/{{ entware_arch }}-k{{ entware_version }}/installer/generic.sh"
    dest: "/tmp/generic.sh"
    mode: "0775"

- name: Install entware
  when: not entware_release.stat.exists
  ansible.builtin.command:
    cmd: /bin/sh /tmp/generic.sh
    creates: "{{ entware_root }}/opt/etc/entware_release"

- name: Add entware profile to global profile
  ansible.builtin.blockinfile:
    path: /etc/profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ENTWARE"
    block: |
      [ -r "/opt/etc/profile" ] && . /opt/etc/profile
