---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: firefly-ro
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: firefly-ro
          image: fireflyiii/core:version-6.0.26@sha256:bb046f374823f110ba981c5a9088eb2a6a924514b7c43e94dbe645ea9c9a2578
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              value: production
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: app-key
            - name: APP_LOG_LEVEL
              value: info
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: db-database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: db-port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: db-password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: firefly-ro-secrets
                  key: db-username
            - name: TZ
              value: Europe/MADRID
            - name: TRUSTED_PROXIES
              value: "**"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 10
