---
- name: Setup cgroup options
  ansible.builtin.import_tasks: cgroup.yml
- name: Setup containerd
  ansible.builtin.import_tasks: containerd.yml
- name: Setup nfs
  ansible.builtin.import_tasks: nfs-common.yml
