---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"

includes:
  ansible: .taskfiles/ansible.yml
  k8s: .taskfiles/kubernetes.yml
  linter: .taskfiles/linter.yml
  format: .taskfiles/formatter.yml

tasks:
  default: task -l

  deps:
    desc: Install required packages
    cmds:
      - ansible-galaxy install --role-file "{{.ANSIBLE_DIR}}/requirements.yml" --force
