---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/provision/ansible"

includes:
  ansible: .taskfiles/ansible.yml
  k8s: .taskfiles/kubernetes.yml
  linter: .taskfiles/linter.yml
  format: .taskfiles/formatter.yml

tasks:
  default: task -l
