---
- name: Upgrade transmission packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - transmission-daemon
    - transmission-web
  notify: Restart transmission

# - name: ensure config dir exists
#   file:
#     state: directory
#     path: "{{ transmission_config_dir }}"
#     mode: u=rwx,g=rwx,o=r-x
#     owner: "{{ transmission_system_user }}"
#     group: "{{ transmission_system_user_group }}"

# - name: ensure transmission config files are setup correctly
#   copy:
#     src: settings.json
#     dest: "{{ transmission_config_dir }}/settings.json"
#     mode: u=rw-,g=rw-,o=r--
#     owner: "{{ transmission_system_user }}"
#     group: "{{ transmission_system_user_group }}"
#   notify: Restart transmission

- name: Ensure transmission daemon service exists
  ansible.builtin.copy:
    src: transmission.service
    dest: /etc/systemd/system/transmission.service
    mode: u=rwx,g=--x,o=--x
    owner: root
    group: root
  notify: Restart transmission

- name: Enable transmission daemon service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: transmission
  notify: Restart transmission
