---
- name: Install apt updates
  apt:
    upgrade: dist
    update_cache: true
    autoremove: true
    autoclean: true
  register: result

- name: List installed and updated packages
  shell: |
    set -o pipefail
    grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
  register: result

- name: Show Output
  debug: msg="{{ result.stdout_lines }}"

# TODO Handle dietpi upgrades
# - name: Install dietpi updates
#   shell: dietpi-upgrade 1
