---

- name: Register if there are dietpi updates
  stat:
    path: /run/dietpi/.update_available
  register: dietpi_updates

- name: Updating using dietpi-update
  shell:
    cmd: /boot/dietpi/dietpi-update 1
    stdin: true
  when: dietpi_updates.stat.exists

- name: Register if there are apt updates
  stat:
    path: /run/dietpi/.apt_updates
  register: apt_updates

- name: Update using apt
  apt:
    upgrade: dist
    update_cache: true
    autoremove: true
    autoclean: true
  when: apt_updates.stat.exists
