---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: transmission
spec:
  rules:
    - host: transmission.home.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  name: http
