---
- name: Install software in nas
  hosts: grimmauld
  gather_facts: true
  become: true

  environment:
    PATH: "/opt/bin:{{ ansible_env.PATH }}"

  vars:
    ansible_python_interpreter: "/opt/bin/python3"

  roles:
    - flexget
