---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: homer-config
    files:
      - config.yml
helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    version: 3.3.0
    releaseName: &releaseName homer
    namespace: &releaseNamespace default
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
