apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: default
stringData:
  VIKUNJA_SERVICE_PUBLICURL: ENC[AES256_GCM,data:kQ1WCvJvN80Gsj5Z6CP6B5Zr0Q==,iv:JmsWAi0cAUFgAE6p1i38aOiacnijLLbPtoGbqN+TWXA=,tag:Jsneopif4FkdabyXif4wHw==,type:str]
  VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:mNPiTJ0Q2ZR5W7H3tLCRM3m4pGl9bQbGPQJACBAH8UNqiD/jlOhSdd9L1X0=,iv:N/attvu+9oGIZErql/FRW1kK7pY+jjWqeFYs+yfbYiw=,tag:ep7zj2k7zx0myer8XMnKWw==,type:str]
  VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:Wd2kAtg=,iv:Z2LFIsFLPf3y7OBJHx23PyMpgj2g9s1kP+MocIe/v2c=,tag:qF0YKDfVvl1XLKLWhqDnkA==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:x8Yfe15PJocLA0qM,iv:5swGODyZvpE/QExRfezJnZyMzLsw6eQyx8cJ6jvrjYo=,tag:iLq4Ca139NcH+nJePlp1zg==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:sLHeasuDgw==,iv:fukZNVQI0As1hpGFJTte2Yut66tKzUDNAAfcLAAjnh0=,tag:N3UDx5QmxDD7bnzboRyoOg==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:okSt9qBZA8K16/U=,iv:RoruPrKF+GQ7GJOCc4JrCtH5EAfO9j04t4OkI5RgjZY=,tag:nhPSPuCCSyRu8BJKjpYN4w==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:6SKXbXb2vQ==,iv:Xn8AtwybfEojrI74ormjwJxmaA887+GDMmzdTyoHYHs=,tag:u/2hZVkjYZ79eFSgInkcNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUFsaXI5b3VwdnNKbHUy
        SmRLVjhnUElma0JuNXB0VHhOMWgwcGpaZENrCmF1anNmOEM2MEJUZVl5S0JuWnNO
        a00razZuMHRXUzF0OHNhZGord2JzWk0KLS0tIDFFZ3hTbndVZjlJT0lld2c2b01v
        NThHVDE1ZnV1cHlPRkE1M2RCY2lWNXMKrBTcHsGHkJrjqDoH0ro0jeDg4yq1VX+L
        J0kCxDc24Tn7TnlDCMH4YZKOCQNEJfA4Gg8R3ccFGYgIvbGHYyO8CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T15:00:14Z"
  mac: ENC[AES256_GCM,data:1LXF4YLLFCBV+bQH/6UIHUP5gZxt7Vos8o36RtUdNSGF2JrkS46dlYl6GTC9S4T5521XW0PB2XHcLGcSglZEnn73C9pv0wgG3TZHS+NgJrm5XDGTseeJx/KUNS8gBTBA6A2Ne5/xRMLGj3StTSZXj0ydZ0rR32o3Mmc6A6fplrE=,iv:enEMIgnRW5sZqXnHYHnM6mfjI6Z08u2bfwEI1tceRgE=,tag:v1kevFCRbScMLWBCGn9LsQ==,type:str]
  version: 3.13.3
