apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: default
stringData:
  VIKUNJA_SERVICE_PUBLICURL: ENC[AES256_GCM,data:jQTsZ0C0DL/Tg+qXFMCUWdp3jw==,iv:3W3JosBuly0wxN3Q5UKAECiM4ql+6znh+Fs4c/0cSl0=,tag:jyyDDAf2meGH5vR+3TDUmw==,type:str]
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:oRa9mbUKY1Ld1pRThYxjxkBze0NIrnUm9dsjLTU24jZDl9Jmtn4kdw7J3Tw=,iv:RhwkxUAGEU/F2fRX0IpEYhGf4pHCHxuD40TcIDip4Yc=,tag:OeFRdrTYycb7wUr5oCgxQg==,type:str]
  VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:+Xl/wlg=,iv:X2Cr2jnG3cVMG0LrOIGzB3ZL8AGsajNo0z8YhY9jpus=,tag:Q6EXptHhQAMlSGkCMq5OgQ==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:2Q4ZRfD+FEvsY8xJ,iv:QqkEgN732CP3qDbvwsZde3NWef+quEs0isUBN+pnkLE=,tag:8i1I6vJHbs2Lp8gwWSeK8Q==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:4OHewR3HXg==,iv:HWzS8MIrzLl9BM5oM0zMFTGpsq7wIGCCZqJGtg6lNpE=,tag:LjGpBmzXSr+oGdnyboDjEQ==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:HoIWtQl+eA==,iv:qls1LCcWCuAQE4exuGsNMnRSPLAOmYfKYHkMltB/Euw=,tag:fAAaWdY3U1wHgJfJHHzdaQ==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:VDOlJIpMLUs34+A=,iv:D2gl6UYahrMmnyamWjnqjNa0dKEZ8mVybJcBLtN8MtA=,tag:kommltMCAcq4iq2bHtAjHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWDk3dzR1N1gvc1BFWlI4
        dEJvdUVZK0tKMWJLaE9OdW5XbE9oOFZMaUJnCk5nS0FDaWxzSU1zOWJnTFdFZ0tD
        LzFKUUMvaVJiMXcxa0JmcG0xekplSk0KLS0tIDU2cFpYS0FNU3c4SHpZN3l1RnRy
        d05GNEtPV24vTmdmZGZlQW9VZElubDAKI+sM+Mbd6vcvos7ryLXaIT1TkLZbaExl
        LLPrgZcer6FhFVm65nV2iQX3wvoYJr9LjTwrl9wBTKeZ8KSiQ380Sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T14:34:29Z"
  mac: ENC[AES256_GCM,data:1VvHzUNoa7j2vHuS2I3qZEoYePAca+4Mn9vxiCgKCFCAAstgaRJqF6L5j4Rh9RM/CABUEkT0yz8jijal2Bzy5+LZdhSMeNadRwFZf8rRyYnzOHXhqWvwYsZzjvCAsNt0hjC1FCmlceSI8oWyBu5ilQjJuqsnIvufdTEZuaqSZP8=,iv:f9Hd1ahDiWP20AXFHmg+OOHUSkNpjgVmlpBVBrU+k28=,tag:W1IjOhe3f/+XivlwXZqXzw==,type:str]
  version: 3.13.3
