apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: default
stringData:
  VIKUNJA_SERVICE_PUBLICURL: ENC[AES256_GCM,data:1boKZJopT2M3g0/U/DrST0aOWQ==,iv:9EAZTG7jq4DMu8sVlKJbFCPLPuQLX6CCebJqkgtUeM8=,tag:WGP+u44I6/3vn9KjcN8Bcw==,type:str]
  VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:IfiY2a4=,iv:8ggJXUJlzu1g4wEQAz2DzLI9XOQH7l6ivGsQyWx2UJw=,tag:AlwuK6pjuvZRjePQu3AbKg==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:i+KYyiLS6w4FckBHdsy++pM=,iv:K1EwSu0UKhq6e7zx3Eas3dl4CmYC7dQgK+Hb/CGcHFE=,tag:6eD994AETxRnQbP0R41AVQ==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:NMWlhEcAPQ==,iv:1e0kDjok5BLMIGLyrdHyo2OHe0tru9j7WHkA+Of9aBo=,tag:Nrzy6crZWy+iFklAMLMfSg==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:IDnRltU7kA==,iv:JTAbzgqEIbyYU+YVtd1uXCwEdLUq0Jbt4Vybso6zlpE=,tag:pcGsMs8JpLn12fj40VSVWw==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:UeI7IX91KQxZUE4=,iv:2F8cbCULIBh7fgsNzxQye233qJqYpQl1qBnmivYFwz4=,tag:Qh8fP8LGXO72qzNiQVJWqw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaHRDVXR1YWJyMzNDeDJo
        R2xpcTFlK3NUdlROeGh4T3Q5Y1VIMysxSVRVCldqVHFabjMwTDREQlN0WTlqUkFR
        SHVQeGh0T2t5Uys4QnJCbDdreFJZTnMKLS0tIEtFVU9GL2U3YWUraU5jeEZiV3Bx
        V0tOOUcrSDhOSmlmYVhKTXhhU2xPekkKiEBODXFgYnd+2IuAmbChwlcqBm+uEi69
        n4tvkUGwQOPoB51eU2nXUhFRZz3V8T6/G/x+dUaiN7xfwWFuEaWGCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T08:47:27Z"
  mac: ENC[AES256_GCM,data:uvZlus9W5edY+2glTLc48xZyQXGfh6N+R+G/quoZ5gHalaF0zRy5agEmVM8QTwRKL/SIdiWX8+ZxyQxc23N1F54dplJW1ILAGBA6vbwY+5SQM+XuDlHP3JgWlgcbd6LEPo9LBuks/tGEiTSE0cdYLjU0nmodWku5KzKQY9xX2LQ=,iv:78KIBM7rE+4XpfzWw04AkJ5YX+K1DUOpWHHaoW47Kc4=,tag:ksKwXyW2xH7mDHJmHCv9rw==,type:str]
  version: 3.13.3
