---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          # renovate: datasource=docker depName=vikunja/vikunja
          repository: docker.io/vikunja/vikunja
          tag: "2.6.0"
          pullPolicy: IfNotPresent
        env:
          VIKUNJA_SERVICE_TIMEZONE: Europe/Madrid
          VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"
          VIKUNJA_FILES_BASEPATH: /app/vikunja/files
        envFrom:
          - secretRef:
              name: vikunja-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true

persistence:
  data:
    enabled: true
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
    annotations:
      nfs.io/storage-path: "data"

    advancedMounts:
      main:
        app:
          - path: /app/vikunja/files
            readOnly: false

service:
  app:
    controller: main
    ports:
      http:
        port: 3456

route:
  vikunja:
    enabled: true
    hostnames:
      - "todo.home.es"
    parentRefs:
      - name: gateway
        namespace: networking
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: app
            port: http
