---
kubernetes:
  children:
    masters:
      hosts:
        fluffy1:
          ansible_host: 192.168.1.201
      vars:
        ansible_connection: ssh
        ansible_user: dietpi
    workers:
      hosts:
        fluffy2:
          ansible_host: 192.168.1.202
        fluffy3:
          ansible_host: 192.168.1.203
        fluffy4:
          ansible_host: 192.168.1.204
        fluffy5:
          ansible_host: 192.168.1.205
      vars:
        ansible_connection: ssh
        ansible_user: dietpi
