---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.13.5
          env:
            - name: EXTERNAL_DNS_PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-dns-secrets
                  key: webpassword
          args:
            - --source=ingress
            - --registry=noop
            - --policy=upsert-only
            - --provider=pihole
            - --pihole-server=http://192.168.1.250
            - --pihole-tls-skip-verify
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
