---
- name: Add identity key to authorized keys on host
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop: "{{ ssh_keys }}"
  register: bootstrap_add_identity_keys
  when: ssh_keys is defined and ansible_user is defined

- name: Disable empty password login
  ansible.builtin.lineinfile:
    dest: "{{ openssh_config }}"
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify: Restart sshd

- name: Disable remote root login
  ansible.builtin.lineinfile:
    dest: "{{ openssh_config }}"
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart sshd

- name: Disable password login
  ansible.builtin.lineinfile:
    dest: "{{ openssh_config }}"
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'
  when:
    - bootstrap_add_identity_keys is succeeded
    - not bootstrap_add_identity_keys is skipped
  notify: Restart sshd
