---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: babybuddy
spec:
  rules:
    - host: baby.home.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: babybuddy
                port:
                  name: http
