apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  pihole-webpassword: ENC[AES256_GCM,data:aXxqvp2Y2ArdoH7FLWKZO1anBZBBLbAzfJ91A/g6b1VyfwssGMjYid9sAmE=,iv:N+vggHeLj/rChcStBbWMA0zeBy2u4a8223akQxCWDgM=,tag:zOm8VtQzdXBTzPGYTRqf+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcTN0Vk9MQ0RUTmZlZzc2
        R01wRGh5U1Zrb3RDT0lCTjlvYUFhMGhNUm44Ck9hQXJpeUN0VkpQVHpQRG1SVlZH
        SVp1cG9mQXhvdjhaeHVXbG0xYjBNRm8KLS0tIGJKc2FkNGRaL1N5cCtJb1ZTRVJ1
        azJRbStkRlRibndGb3BmdEp2WWZCNUUKGlqqmihu3+X04AaG1URJyjQ7KQy9ZOsD
        O+uiw6k3inzGy+O0lxYlKhwUJWWbyT3TdM4elNXkv6AzA9oCCfWfWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T04:48:40Z"
  mac: ENC[AES256_GCM,data:0UXuxUnFkOhWlt9ETAUQ72h1DaagEwaV1OPGxXcXEhYu4tmOIYfZy6qF2BSZ3aXPkmPWlDw6hPI6PD4uF2B8F9s4fLfISQcRoLQcy8raeZZKrzCfwFwKdKKnPrDVm6xNBJCPeUWkyUxAZfFyF2+/ija5cQNxVcMtr5v41Fa8kpk=,iv:ztuuiaKWhSoyHlmue1BXwBe2o5eUc0cNquGqYUN/MZI=,tag:EpvI7GmTB+DgiIHhEVDC+A==,type:str]
  version: 3.13.3
