apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  pihole-webpassword: ENC[AES256_GCM,data:vUxx9Qv/3FEPaQKM8PsON1tH/VBS8LWs1ECDfwsMf7lsuuIRlyoqhdxWGQ8=,iv:lIiyrrHPhX5iNJi+0va/Tb0WTRGtp3byny3IsDcQaGY=,tag:mhfIL4sXIwBj5EGDJF7JrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQTZteGRYTlF5UHZvRDhI
        dHN5bGR5NTAzNjdLbUFQTGxwVG44dUtSYW1NCm4xdWlDMnhQVEE2ZlNHdFZJdzY3
        MUNBS3BqaXh6VFJnOFdQbjdrRCtVaEEKLS0tIEJsUEhmeHJhbkdIT3dVbzlQUTNO
        WlhYeWdadk5EWU5OWnlQTHlKVXc4bHMK9q1K4LsKg1IcuC0P+dmsR3Yoem8+Ea8M
        v4C81is7fvLUeH5gQAjDvdmNXE18s3tP46mTDPjVMUvkC8Q620vlTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T05:18:56Z"
  mac: ENC[AES256_GCM,data:u2o5XkjGR7v2W2MiN5RtNMEjjccGcAeCfjSt/Oe1XS2fBW72zifk6HkotSMsHrN/YaEP+tLxN5AMSRohKzNUMg9k0vhIeg0lmyqtCC44lRES7OwXJ2WDWsvpYDW4YHwn5FtApcCikweECGCKkeBuAIchcD9/6u3ckQZJ415eu4M=,iv:xKmkJr2He3De5Rcg8R3ZiBfVqGRwjX1iyvt9/OlGVlA=,tag:9dR9ln+ikAe4igQ20l12rQ==,type:str]
  version: 3.13.3
