---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: firefly-iii
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: firefly-iii
          image: fireflyiii/core:version-5.7.15
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              value: production
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: app-key
            - name: APP_LOG_LEVEL
              value: info
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: db-database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: db-port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: db-password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: db-username
            - name: MAIL_MAILER
              value: smtp
            - name: MAIL_HOST
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_ENCRYPTION
              value: tls
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: mail-from
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: mail-password
            - name: TZ
              value: Europe/MADRID
            - name: TRUSTED_PROXIES
              value: "**"
            - name: STATIC_CRON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: firefly-secrets
                  key: static-cron-token
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 10
