---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: firefly-iii-upload-claim
  annotations:
    nfs.io/storage-path: "firefly_uploads"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
