---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.0
    releaseName: &releaseName metallb
    namespace: &releaseNamespace metallb-system
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Helm
