---
- name: Set facts for Linux
  ansible.builtin.set_fact:
    k3sup: k3sup
  when: ansible_facts['system'] == 'Linux'

- name: Set facts for MacOS
  ansible.builtin.set_fact:
    k3sup: k3sup-darwin
  when: ansible_facts['system'] == 'Darwin' and ansible_facts['machine'] == "x86_64"

- name: Set facts for MacOS ARM
  ansible.builtin.set_fact:
    k3sup: k3sup-darwin-arm64
  when: ansible_facts['system'] == 'Darwin' and ansible_facts['machine'] == "arm64"

- name: Install k3sup binary
  ansible.builtin.get_url:
    url: "https://github.com/alexellis/k3sup/releases/download/{{ k3sup_version }}/{{ k3sup }}"
    dest: "/tmp/k3sup"
    mode: 0755
  register: installk3sup
