---

- name: Set facts for Linux
  set_fact:
    k3sup: k3sup
  when: ansible_facts['system'] == 'Linux'

- name: Set facts for MacOS
  set_fact:
    k3sup: k3sup-darwin
  when: ansible_facts['system'] == 'Darwin'

- name: Install k3sup binary
  get_url:
    url: "https://github.com/alexellis/k3sup/releases/download/{{ k3sup_version }}/{{ k3sup }}"
    dest: "/tmp/k3sup"
    mode: 0755
  register: installk3sup
