---
- name: Upgrade python installation
  community.general.opkg:
    name:
      - gcc
      - python3
      - python3-dev
      - python3-pip
    state: present
    update_cache: true

- name: Pip self-update # noqa package-latest
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
    state: latest
