---
- name: Docker install
  block:
    - name: Docker | check if docker is installed
      ansible.builtin.lineinfile:
        path: /boot/dietpi/.installed
        line: "aSOFTWARE_INSTALL_STATE[162]=2"
        state: absent
      check_mode: true
      changed_when: false
      register: check_docker

    - name: Docker | install docker # noqa no-handler no-changed-when
      ansible.builtin.command:
        cmd: /boot/dietpi/dietpi-software install 162
      when: not check_docker.found

- name: Containerd clenup
  block:
    - name: Containerd | Create containerd-clean up periodic task
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: "0644"
        remote_src: false
      loop:
        - containerd-cleanup.service
        - containerd-cleanup.timer

    - name: Containerd | Enable timer # noqa no-handler
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        daemon_reload: true
        masked: false
        state: started
      loop:
        - containerd-cleanup.timer

- name: Docker clenup
  block:
    - name: Docker | Create docker-clean up periodic task
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: "0644"
        remote_src: false
      loop:
        - docker-cleanup.service
        - docker-cleanup.timer

    - name: Docker | Enable timer # noqa no-handler
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        daemon_reload: true
        masked: false
        state: started
      loop:
        - docker-cleanup.timer
