---
# Flux Kustomization for the Local Path Provisioner (node-local dynamic storage).
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/fluffy/apps/kube-system/local-path-provisioner
  prune: true
  dependsOn:
    - name: apps-kube-system
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
