---
- name: Get absolute path to this Git repository
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.command: "git rev-parse --show-toplevel"
  register: repo_abs_path

- name: Create master server with k3s "{{ k3s_version }}"
  command:
  args:
    argv:
      - /tmp/k3sup
      - install
      - --ip
      - "{{ hostvars[item].ansible_host}}"
      - --user
      - "{{ ansible_user }}"
      - --k3s-version
      - "{{ k3s_version }}"
      - --k3s-extra-args
      - "{{ k3s_extra_args }}"
      - --local-path
      - "{{ repo_abs_path.stdout }}/provision/kubeconfig"
  with_items: "{{ groups['masters'] }}"
  register: master_created
