---
- name: "Create agent and join {{ groups.masters.0 }} with k3s {{ k3s_version }}" # noqa no-handler
  ansible.builtin.command:
    argv:
      - /tmp/k3sup
      - join
      - --ip
      - "{{ hostvars[item].ansible_host }}"
      - --server-ip
      - "{{ hostvars[groups.masters.0].ansible_host }}"
      - --user
      - "{{ hostvars[item].ansible_user }}"
      - --k3s-version
      - "{{ k3s_version }}"
  with_items: "{{ groups['workers'] }}"
  when: master_created is succeeded
