---
title: "Home Dashboard"
subtitle: "Welcome back!"
logo: "https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/kubernetes-512.png"
#icon: "fas fa-paw"
header: true
footer: false
theme: default

links:
- name: "GitHub"
  icon: "fab fa-github"
  url: "https://github.com/"
- name: "GitLab"
  icon: "fab fa-gitlab"
  url: "https://gitlab.com/"
- name: "Reddit"
  icon: "fab fa-reddit-alien"
  url: "https://reddit.com/"

services:
- name: "Applications"
  icon: "fas fa-laptop-code"
  items:
  - name: "Firefly III"
    subtitle: "A free and OSS personal finance manager"
    logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/firefly.png"
    tag: "money"
    url: "http://firefly.home.es/"

  - name: "FiDI"
    subtitle: "This tool will help you import data into Firefly III"
    logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/firefly.png"
    tag: "money"
    url: "http://fidi.home.es/"

  - name: "Vikunja"
    subtitle: TODO App
    logo: "https://kolaente.dev/vikunja/theme/raw/branch/main/static/images/vikunja.png"
    tag: "tasks"
    url: "http://todo.home.es/"

- name: "Tools"
  icon: "fas fa-network-wired"
  items:
  - name: "Pi Hole"
    subtitle: "A black hole for Internet advertisements"
    logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/pihole.png"
    tag: "network"
    url: "http://pi.hole/admin"
    type: "PiHole"

  - name: "k3s dashboard"
    subtitle: "Web-based UI for Kubernetes clusters"
    logo: "https://styles.redditmedia.com/t5_33f68/styles/communityIcon_w3qxa8j08vj01.png"
    tag: "dashboard"
    url: "http://k3s.home.es"
