---
- name: "Create agent and join {{ groups.servers.0 }} with k3s {{ k3s_version }}" # noqa no-handler no-changed-when name[template]
  ansible.builtin.command:
    argv:
      - /tmp/k3sup
      - join
      - --ip
      - "{{ hostvars[item].ansible_host }}"
      - --server-ip
      - "{{ hostvars[groups.servers.0].ansible_host }}"
      - --user
      - "{{ hostvars[item].ansible_user }}"
      - --k3s-version
      - "{{ k3s_version }}"
      - --k3s-extra-args
      - "{{ common_extra_args }}"
  with_items: "{{ groups['agents'] }}"
  when: k3s_server_created is succeeded
