---

- name: Create agent and join {{ groups.masters.0 }} with k3s {{ k3s_version }}
  command:
  args:
    argv:
      - /tmp/k3sup
      - join
      - --ip
      - "{{ hostvars[item].ansible_host }}"
      - --server-ip
      - "{{ hostvars[groups.masters.0].ansible_host }}"
      - --user
      - "{{ ansible_user }}"
      - --k3s-version
      - "{{ k3s_version }}"
      - --k3s-extra-args
      - "--docker"
  with_items: "{{ groups['workers'] }}"
  when: master_created is succeeded