---
- name: Get absolute path to this Git repository # noqa command-instead-of-module no-changed-when
  become: false
  run_once: true
  ansible.builtin.command:
    cmd: "git rev-parse --show-toplevel"
  register: k3s_repo_abs_path

- name: "Create server with k3s {{ k3s_version }}" # noqa no-changed-when
  ansible.builtin.command:
    argv:
      - /tmp/k3sup
      - install
      - --ip
      - "{{ hostvars[item].ansible_host }}"
      - --user
      - "{{ hostvars[item].ansible_user }}"
      - --k3s-version
      - "{{ k3s_version }}"
      - --k3s-extra-args
      - "{{ servers_extra_args }} {{ common_extra_args }}"
      - --local-path
      - "{{ k3s_repo_abs_path.stdout }}/kubeconfig"
  with_items: "{{ groups['servers'] }}"
  register: k3s_server_created
