---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    prometheus:
      scrapeAnnotations: false
      rbacPrometheus: false
      podMonitor.enabled: false
      serviceMonitor.enabled: false
      prometheusRule.enabled: false
    speaker.frr.enabled: false
  uninstall:
    keepHistory: false
