---
- name: DietPi bootstrap config generator
  hosts: localhost
  gather_facts: false

  vars:
    file: /tmp/dietpi.txt

  tasks:
    - name: Download dietpi.txt from MichaIng/DietPi
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
        dest: "{{ file }}"
        checksum: sha256:0990bdb1af35c5a779314c9213395e11cc47bf9949a9aa29662004938ba1034c
        mode: u=rw,g=r,o=r

    - name: Setup Locale
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_LOCALE'
        line: 'AUTO_SETUP_LOCALE=en_US.UTF-8'

    - name: Setup Keyboard
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_KEYBOARD_LAYOUT'
        line: 'AUTO_SETUP_KEYBOARD_LAYOUT=us'

    - name: Setup TZ
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_TIMEZONE'
        line: 'AUTO_SETUP_TIMEZONE=Europe/Madrid'

    - name: Enable DHCP to static ip
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_DHCP_TO_STATIC'
        line: 'AUTO_SETUP_DHCP_TO_STATIC=1'

    - name: Disable swap
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_SWAPFILE_SIZE'
        line: 'AUTO_SETUP_SWAPFILE_SIZE=0'

    - name: Disable HDMI/video
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_HEADLESS'
        line: 'AUTO_SETUP_HEADLESS=0'

    - name: Choose OpenSSH as ssh server
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_SSH_SERVER_INDEX'
        line: 'AUTO_SETUP_SSH_SERVER_INDEX=-2'

    - name: Setup RAMlog with hourly clear
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_LOGGING_INDEX'
        line: 'AUTO_SETUP_LOGGING_INDEX=-1'

    - name: Enable unattended install
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^AUTO_SETUP_AUTOMATED'
        line: 'AUTO_SETUP_AUTOMATED=1'

    - name: Setup python auto-install
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        # regexp: '^#?AUTO_SETUP_INSTALL_SOFTWARE_ID'
        insertafter: '^#?AUTO_SETUP_INSTALL_SOFTWARE_ID'
        line: 'AUTO_SETUP_INSTALL_SOFTWARE_ID=130'

    - name: DietPi Survey opt out
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^SURVEY_OPTED_IN'
        line: 'SURVEY_OPTED_IN=0'

    - name: Disable serial console
      ansible.builtin.lineinfile:
        dest: "{{ file }}"
        regexp: '^CONFIG_SERIAL_CONSOLE_ENABLE'
        line: 'CONFIG_SERIAL_CONSOLE_ENABLE=0'

    - name: Generate dietpi.txt file
      ansible.builtin.copy:
        src: "{{ file }}"
        dest: "../dietpi_{{ item }}.txt"
        mode: u=rw,g=r,o=r
      loop: "{{ groups['kubernetes'] }}"

    - name: Set hostname
      ansible.builtin.lineinfile:
        dest: "../dietpi_{{ item }}.txt"
        regexp: '^AUTO_SETUP_NET_HOSTNAME'
        line: 'AUTO_SETUP_NET_HOSTNAME= {{ item }}'
      loop: "{{ groups['kubernetes'] }}"

    - name: Enable static ip
      ansible.builtin.lineinfile:
        dest: "../dietpi_{{ item }}.txt"
        regexp: '^AUTO_SETUP_NET_USESTATIC'
        line: 'AUTO_SETUP_NET_USESTATIC=1'
      loop: "{{ groups['kubernetes'] }}"

    - name: Set static ip
      ansible.builtin.lineinfile:
        dest: "../dietpi_{{ item }}.txt"
        regexp: '^AUTO_SETUP_NET_STATIC_IP'
        line: 'AUTO_SETUP_NET_STATIC_IP={{ hostvars[item].ansible_host }}'
      loop: "{{ groups['kubernetes'] }}"
