---
- name: DietPi bootstrap config generator
  hosts: localhost
  gather_facts: false

  # TODO: Install python (id: 130)

  tasks:
    - name: Generate dietpi.txt file
      ansible.builtin.template:
        src: templates/dietpi.txt.j2
        dest: "../dietpi_{{ item }}.txt"
      loop: "{{ groups['kubernetes'] }}"
