---
- name: Generate dietpi image
  ansible.builtin.copy:
    src: "{{ output_dir.path }}/{{ img }}"
    dest: "{{ output_dir.path }}/DietPi_{{ item }}.img"
    mode: u=rw,g=r,o=r
  register: image

- name: Loopback register
  become: true
  ansible.builtin.command:
    cmd: "losetup -f"
  register: loopback
  changed_when: false

- name: Loopback attach
  become: true
  ansible.builtin.command:
    cmd: "losetup {{ loopback.stdout }} -P {{ image.dest }}"
  changed_when: false

- name: Mount boot partition
  become: true
  ansible.posix.mount:
    src: "/dev/loop0p1"
    fstype: "none"
    state: "ephemeral"
    path: "{{ mount_dir.path }}"

- name: Copy dietpi.txt # noqa risky-file-permissions
  become: true
  ansible.builtin.copy:
    src: "{{ output_dir.path }}/dietpi_{{ item }}.txt"
    dest: "{{ mount_dir.path }}/dietpi.txt"

- name: Umount boot partition
  become: true
  ansible.posix.mount:
    state: "unmounted"
    path: "{{ mount_dir.path }}"

- name: Loopback dettach
  become: true
  ansible.builtin.command:
    cmd: "losetup -d {{ loopback.stdout }}"
  changed_when: false
