---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: importer
    repo: https://firefly-iii.github.io/kubernetes
    version: 1.4.9
    releaseName: &releaseName firefly-iii-data-importer
    namespace: &releaseNamespace default
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Helm
