---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    version: 3.7.3
    releaseName: &releaseName vikunja
    namespace: &releaseNamespace default
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
  nfs.io/storage-path: vikunja
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Helm
