---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.3/charts/library/common/values.schema.json
controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          repository: docker.io/vikunja/vikunja
          tag: 0.24.5
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: vikunja-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true

persistence:
  data:
    enabled: true
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true

    advancedMounts:
      main:
        app:
          - path: /app/vikunja/files
            readOnly: false

service:
  app:
    controller: main
    ports:
      http:
        port: 3456

ingress:
  vikunja:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: todo.home.es.
      external-dns.alpha.kubernetes.io/target: home.es.
    hosts:
      - host: todo.home.es
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
