---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  externalIPs:
    - 192.168.1.201
  type: NodePort
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 8000
    - protocol: TCP
      port: 8000
      name: admin
      targetPort: 9000
