---
repositories:
 - name: traefik
   url: https://traefik.github.io/charts

releases:
- name: traefik
  namespace: networking
  chart: traefik/traefik
  version: 26.1.0
  values:
    - ./values.yml
  historyMax: 1
  disableValidation: false
  disableValidationOnInstall: true
