---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    version: 3.0.3
    releaseName: &releaseName external-dns-pihole
    namespace: &releaseNamespace networking
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
namespace: *releaseNamespace
resources:
  - ./rbac.yml
