---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.17.0
    releaseName: &releaseName external-dns-pihole
    namespace: &releaseNamespace networking
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Helm
namespace: *releaseNamespace
