---
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    pihole-webpassword: ENC[AES256_GCM,data:UnzJRqPP,iv:fWapOykRC5bnkB607hIz/3EvnoE5MU+Hv97BBA9Dc+E=,tag:0qhLEeCPOasKbXvGyWueeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fr2tvfvd65sqrapmft0w44ukg4v5g2ar9su9229w0737k7vtuc3sy0d9ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUdzTkNCRVNsOG1OQVdi
            NnpWOGRwTVdwcE41SGZSUmRoZDZ0d1FkcVUwClRrZUZvbWpIM1VTaFo0MzNGdnBM
            d0QyOVRPTlVjQUlITTgxTU9jd0V6ZW8KLS0tIHVRZWdRYUJIZDNjSzl3azlHdk5L
            c3RSdFRPM0szdFVQWTVYekRDL2hHVEEKCJynGcr5nt8SEhy1OhAqI1W+i3HKmUWq
            LtnhHxBr1yrdR/+Au7Z7qQBtpLWD6Lqja+PKQYrxJGRnvytLD8ftOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T05:17:14Z"
    mac: ENC[AES256_GCM,data:wKBd2i4VfU6ao5W6BIoYT4PisLS93aB4cZSVVNSGzdjWSMiGfKt+Xx6Tf2SQq33UdSmXIHPsnhVC635dwC3Te2JTSer/GX7cN79N+SBwJYbPzbME2wv9GCLkFhQUUtABub0p6jUaS/TRZIvvQXlreI7HjOXEQnlGdE/QAtKahzM=,iv:JcIn1aaJnmTJ9SBeJOAVt77BHjtdOaQh1QhEfIk4XWE=,tag:f1Nl7M89ozvsrXYIF2lvxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
