---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nfs-subdir-external-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.18
    releaseName: &releaseName nfs-subdir-external-provisioner
    namespace: &releaseNamespace default
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
