---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traefik
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:2.10.5
          args:
            - --entrypoints.web.address=:8000
            - --entryPoints.traefik.address=:9000
            - --providers.kubernetesingress=true
            - --api.dashboard=true
            - --api.insecure=true
            - --log.level=INFO
          ports:
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 9000
