---
# Flux Kustomization for the kube-system namespace workloads.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-kube-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/fluffy/apps/kube-system
  prune: true
  dependsOn:
    - name: apps
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system