---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: v4.7.0
    releaseName: &releaseName csi-driver-nfs
    namespace: &releaseNamespace kube-system
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
commonLabels:
  app.kubernetes.io/managed-by: Helm
