---
- name: Cluster Installation
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - name: Install k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed

    - name: Kubeconfig
      vars:
        repository_base: "{{ lookup('ansible.builtin.pipe', 'git rev-parse --show-toplevel') }}"
      block:
        - name: Kubeconfig | Copy kubeconfig to the project directory
          when: k3s_primary_control_node
          ansible.builtin.fetch:
            src: /etc/rancher/k3s/k3s.yaml
            dest: "{{ repository_base }}/kubeconfig"
            flat: true

        - name: Kubeconfig | Update kubeconfig with the correct load balancer address
          delegate_to: localhost
          become: false
          ansible.builtin.replace:
            path: "{{ repository_base }}/kubeconfig"
            regexp: https://127.0.0.1:6443
            replace: "https://{{ hostvars[groups.servers.0].ansible_host }}:6443"
