---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  interval: 10m
  url: https://fluxcd-community.github.io/helm-charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  releaseName: flux
  chart:
    spec:
      chart: flux2
      version: 2.12.3
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  values:
    imageAutomationController:
      create: false
      serviceAccount:
        create: false
    imageReflectionController:
      create: false
      serviceAccount:
        create: false
    notificationController:
      create: false
      serviceAccount:
        create: false
  install:
    crds: CreateReplace
    createNamespace: true
  postRenderers:
    - kustomize:
        patches:
          # Remove the network policies that does not work with k3s
          - patch: |
              $patch: delete
              apiVersion: networking.k8s.io/v1
              kind: NetworkPolicy
              metadata:
                name: not-used
            target:
              group: networking.k8s.io
              kind: NetworkPolicy
