---
- name: Check if containerd (docker) is installed
  ansible.builtin.lineinfile:
    path: /boot/dietpi/.installed
    line: "aSOFTWARE_INSTALL_STATE[162]=2"
    state: present
  check_mode: true
  register: docker

- name: Install containerd (docker) # noqa no-handler
  ansible.builtin.command:
    cmd: /boot/dietpit/dietpi-software install 162
  when: docker is changed

- name: Create containerd-clean up periodic task
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    remote_src: false
  loop:
    - containerd-cleanup.service
    - containerd-cleanup.timer
  register: systemd

- name: Enable timer # noqa no-handler
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - containerd-cleanup.service
    - containerd-cleanup.timer
