---
- name: Check if docker is installed
  lineinfile:
    path: /boot/dietpi/.installed
    line: "aSOFTWARE_INSTALL_STATE[162]=2"
    state: present
  check_mode: true
  register: docker

- name: Install docker
  shell: /boot/dietpi/dietpi-software install 162
  when: docker is changed
