- op: replace
  path: /spec/template/spec/containers/0/livenessProbe
  value: null
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe
  value: null
- op: replace
  path: /spec/template/spec/containers/0/startupProbe
  value: null
