---
when:
  branch: main
  event: [push, pull_request]

steps:
  build:
    image: python:3.11
    commands:
      # Install go-task/task
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      # Install ansible-lint and yamllint
      - pip3 install ansible-lint yamllint

      # Run lint
      - bin/task deps
      - bin/task linter:ansible
      - bin/task linter:yaml
