---
when:
  - branch: main
    event: [push, pull_request]
    path: ["docs/**", "mkdocs.yml", "flake.*", ".woodpecker/.site.yml"]

steps:
  - name: build
    image: nixos/nix:2.25.5
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build .#site
      - mkdir public
      - cp -ar result/. public/

  - name: deploy
    image: alpine/git:v2.47.1
    environment:
      BOT_EMAIL:
        from_secret: bot_email
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - WORKDIR=`mktemp -d`
      - cp _redirects $WORKDIR || true
      - cp .domains $WORKDIR || true
      - cp -ar public/. $WORKDIR/
      - cd $WORKDIR
      - git init
      - git config user.name "JesusMtnez-bot"
      - git config user.email "$${BOT_EMAIL}"
      - git checkout --orphan pages
      - git add --all .
      - git commit --message "Deploy pages"
      - git push --force https://$${CODEBERG_TOKEN}@codeberg.org/$CI_REPO pages
    when:
      - event: push
        branch: main
