---
when:
  branch: main
  path: ["docs/**", "mkdocs.yml", "flake.*", ".woodpecker/.site.yml"]

steps:
  build:
    image: nixos/nix:2.24.5
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build .#site
      - mkdir public
      - cp -ar result/. public/

  deploy:
    image: alpine/git:v2.45.2
    secrets:
      - codeberg_token
      - bot_email
    commands:
      - WORKDIR=`mktemp -d`
      - cp _redirects $WORKDIR || true
      - cp .domains $WORKDIR || true
      - cp -ar public/. $WORKDIR/
      - cd $WORKDIR
      - git init
      - git config user.name "JesusMtnez-bot"
      - git config user.email "$BOT_EMAIL"
      - git checkout --orphan pages
      - git add --all .
      - git commit --message "Deploy pages"
      - git push --force https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO pages
    when:
      event: push
      branch: main
