---
when:
  event: [cron, manual]
  branch: main
  cron: update_flakes

steps:
  update-lockfile:
    image: nixos/nix:2.24.2
    secrets:
      - codeberg_token
      - bot_email
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - git config user.name "JesusMtnez-bot"
      - git config user.email "$BOT_EMAIL"
      - git switch -c update_flake
      - nix --option commit-lockfile-summary "update flake.lock" flake update --commit-lock-file
      - git push --force https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO update_flake

  create-pr:
    image: johnwalkerx/gitea-pull-request-create-plugin:latest
    settings:
      gitea_address: https://codeberg.org
      gitea_token:
        from_secret: codeberg_token
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      branch: update_flake
      base_branch: main
      pr_title: "chore(flake): update flake.lock"
      skip_on_missing_branch: true
      close_pr_if_empty: true
      delete_branch_if_pr_empty: true
      delete_branch_after_merge: true
