---
- name: Docker
  block:
    - name: Docker | check if docker is installed
      ansible.builtin.lineinfile:
        path: /boot/dietpi/.installed
        line: "aSOFTWARE_INSTALL_STATE[162]=2"
        state: absent
      check_mode: true
      changed_when: false
      register: check_docker

    - name: Docker | install docker # noqa no-handler no-changed-when
      ansible.builtin.command:
        cmd: /boot/dietpi/dietpi-software install 162
      when: not check_docker.found
