---
name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25

      - name: "Lint ANSIBLE files"
        run: nix develop -c task linter:ansible

      - name: "Lint YAML files"
        run: nix develop -c task linter:yaml
