---
name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v22

      - name: "Lint ANSIBLE files"
        run: nix develop -c task linter:ansible

      - name: "Lint YAML files"
        run: nix develop -c task linter:yaml
